# Generated by Django 6.0.3 on 2026-04-05 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('G', 'En Archivo de Gestión'), ('P', 'Transferencia Pendiente'), ('C', 'Aceptado en Archivo Central'), ('R', 'Rechazado')], default='G', max_length=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(auto_now_add=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('archivo_digital', models.FileField(blank=True, null=True, upload_to='prestamos/digital/', verbose_name='Documento Digitalizado')),
                ('observaciones_fisicas', models.TextField(blank=True, null=True, verbose_name='Notas del estado físico')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del Acta')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('creacion', 'En Creación'), ('enviada', 'Enviada a Central'), ('finalizada', 'Finalizada')], default='creacion', max_length=20)),
                ('usuario_gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarpetaTransferida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula/ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('nombre_carpeta', models.CharField(max_length=255, verbose_name='Asunto/Título')),
                ('folios', models.PositiveIntegerField(default=0, verbose_name='Folios')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('comentarios_central', models.TextField(blank=True, null=True, verbose_name='Observaciones Central')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='gestion.transferencia')),
            ],
        ),
    ]
